name: Apply Style

on:
  issue_comment:
    types: [created]

jobs:
  apply-style:
    if: startsWith(github.event.comment.body, '/style')
    name: Apply Style to Source
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout pull request
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      - name: Apply style updates
        uses: ./.github/actions/apply-style

      - name: Comment on PR
        run: |
          COMMENT_URL=$(jq -r .issue.pull_request.url < $GITHUB_EVENT_PATH || jq -r .issue.url < $GITHUB_EVENT_PATH)
          COMMENT_BODY="Style check completed successfully!"
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d "{\"body\":\"$COMMENT_BODY\"}" $COMMENT_URL/comments
