name: Apply Style

on:
  issue_comment:
    types: [created]

jobs:
  apply-style:
    if: startsWith(github.event.comment.body, '/style')
    name: Apply Style to Source
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking out from PR #${{ github.event.issue.number }}"
          hub pr checkout ${{ github.event.issue.number }}

      - name: Apply style updates
        uses: ./.github/actions/apply-style

      - name: Push changed files
        run: |
          printf "GitHub Actor: ${GITHUB_ACTOR}\n"
          git config user.name "Agent Style"
          git config user.email "no-reply@llnl.gov"
          if [ -n "$(git status --porcelain)" ]; then
            git commit -am 'Apply style updates'
            git push
          fi

      - name: Comment on PR
        run: |
          COMMENT_URL=$(jq -r .issue.pull_request.url < $GITHUB_EVENT_PATH || jq -r .issue.url < $GITHUB_EVENT_PATH)
          COMMENT_BODY="Style check completed successfully!"
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d "{\"body\":\"$COMMENT_BODY\"}" $COMMENT_URL/comments
